
name: add user to team

on:
  push:
    branches: [ main ]
    
env:
#  TEAM_NAME: "${{ github.event.inputs.repo-name }}"
  ORG_NAME: "${{ secrets.ORGANIZATION }}"
#  ACTION: "action"
  
jobs:
  assign-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assign or remove users to TEAM 
        run: |
          IFS=',' read -r ACTION TEAM_NAME < <(head -n 1 Add-or-Remove-User-to-TEAM.csv)
          echo "Action: $ACTION"
          echo "team name: $TEAM_NAME"
          
          if [ $ACTION == "add-user" ]; then
            while IFS=',' read -r USERNAME ROLE || [ -n "$USERNAME" ]; do
              if [ -z "$ROLE" ]; then
                ROLE="member"
              fi
              echo "Username: $USERNAME"
              echo "Role: $ROLE"
              echo "https://api.github.com/repos/${{ env.ORG_NAME }}/$TEAM_NAME/collaborators/$USERNAME"
              curl -X PUT \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
              "https://api.github.com/orgs/${{ env.ORG_NAME }}/teams/$TEAM_NAME/memberships/$USERNAME" \
              --data '{"role": "'$ROLE'"}'
            done < <(tail -n +2 Add-or-Remove-User-to-TEAM.csv)
            
          elif [ $ACTION == "remove-user" ]; then
           while IFS=',' read -r USERNAME ROLE || [ -n "$USERNAME" ]; do
             curl -X DELETE -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }} " -s "https://api.github.com/orgs/${{ env.ORG_NAME }}/teams/$TEAM_NAME/memberships/$USERNAME" 
           done < <(tail -n +2 Add-or-Remove-User-to-TEAM.csv)  
            
          fi
          
      - name: Upload CSV artifact
        uses: actions/upload-artifact@v2
        with:
          name: user-roles-csv
          path: Add-or-Remove-User-to-TEAM.csv
          
        
